<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Robot Constants -->
  <xacro:property name="PI" value="3.14159" />
  <xacro:property name="base_w" value="0.2" />
  <xacro:property name="base_l" value="0.15" />
  <xacro:property name="base_h" value="0.05" />
  <xacro:property name="wheel_r" value="0.033" />
  <xacro:property name="wheel_len" value="0.02" />
  <xacro:property name="z_offset" value="${wheel_r}" />

  <!-- Materials -->
  <material name="CarBody">
    <color rgba="0.2 0.2 0.8 1.0"/> <!-- Metallic Blue -->
  </material>

  <material name="WheelMaterial">
    <color rgba="0.05 0.05 0.05 1.0"/> <!-- Dark Rubber -->
  </material>

  <!-- Base Footprint -->
  <link name="base_footprint"/>
  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${wheel_r}" rpy="0 0 0"/>
  </joint>

  <!-- Base Link -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${base_h}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_w} ${base_l} ${base_h}"/>
      </geometry>
      <material name="CarBody"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${base_h * 0.5}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_w} ${base_l} ${base_h}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.3"/>
      <origin xyz="0 0 ${base_h * 0.5}" rpy="0 0 0"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
    </inertial>
  </link>

  <!-- Left Front Wheel -->
  <link name="left_front_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="${PI * 0.5} 0 0"/>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_r}"/>
      </geometry>
      <material name="WheelMaterial"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${PI * 0.5} 0 0"/>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_r}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.3"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="left_front_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_front_wheel"/>
    <origin xyz="${base_l * 0.5} ${base_w * 0.5} ${z_offset}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- Left Rear Wheel -->
  <link name="left_rear_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="${PI * 0.5} 0 0"/>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_r}"/>
      </geometry>
      <material name="WheelMaterial"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${PI * 0.5} 0 0"/>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_r}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.3"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="left_rear_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_rear_wheel"/>
    <origin xyz="-${base_l * 0.5} ${base_w * 0.5} ${z_offset}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- Right Front Wheel -->
  <link name="right_front_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="${PI * 0.5} 0 0"/>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_r}"/>
      </geometry>
      <material name="WheelMaterial"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${PI * 0.5} 0 0"/>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_r}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.3"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="right_front_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_front_wheel"/>
    <origin xyz="${base_l * 0.5} -${base_w * 0.5} ${z_offset}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- Right Rear Wheel -->
  <link name="right_rear_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="${PI * 0.5} 0 0"/>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_r}"/>
      </geometry>
      <material name="WheelMaterial"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${PI * 0.5} 0 0"/>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_r}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.3"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="right_rear_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_rear_wheel"/>
    <origin xyz="-${base_l * 0.5} -${base_w * 0.5} ${z_offset}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

</robot>
